### ISSUE TITLE
视频播放崩溃，你播放用的是IJK 还是vitamio 呢

### ISSUE THREAD

**Issue by Mongolian** [HotBitmapGG/bilibili-android-client#1]

**Comment by HotBitmapGG** [comment]
视频播放用的是Vitamio 直播播放用的是ijkplayer，崩溃的话 可以把错误日志发上来看一下，

**Comment by Antine** [comment]
代码写的不错的说,既然里面都集成了IJK做直播和弹幕了 再用vitamio做视频播放有些多余了

**Comment by HotBitmapGG** [comment]
@Antine  嗯 是的 因为之前没有做直播的内容 后来抓到了接口 就把这个模块加了上去，因为接口返回的信息只有播放地址的url 所以为了方便就直接用了B站的ijkplayer直接播放了 后期有时间在把这块整理一下,目前还在完善功能 重构代码。

**Comment by HotBitmapGG** [comment]
没有错误日志,我也无法定位，暂时先关闭了,目前已经集成bugly了，方便定位问题.

**Comment by Antine** [comment]
我下载代码打包后也是播放视频崩溃,报classLoader什么错 后面查了下是android studio Instant Run造成的关掉 热编译就ok了
