### ISSUE TITLE
无法运行，报这样的错误~~~~(>_<)~~~~

### ISSUE THREAD

**Issue by helloworld107** [HotBitmapGG/bilibili-android-client#11]
H:\SangGuiGu\bilibili-master-x\app\src\main\java\com\hotbitmapgg\ohmybilibili\network\RetrofitHelper.java
Error:(19, 48) 错误: OriginalRankService在com.hotbitmapgg.ohmybilibili.network.api中不是公共的; 无法从外部程序包中对其进行访问
Error:(437, 19) 错误: 找不到符号
符号:   类 OriginalRankService
位置: 类 RetrofitHelper
Error:Execution failed for task ':app:compileDebugJavaWithJavac'.

> Compilation failed; see the compiler error output for details.

**Comment by HotBitmapGG** [comment]
@helloworld107 我这边编译是没有问题啊

**Comment by HotBitmapGG** [comment]
@helloworld107 现在可以了嘛？

**Comment by helloworld107** [comment]
我再试试

**Comment by HotBitmapGG** [comment]
@helloworld107 这个你对应你的编译环境修改下就可以了 我这边是没有问题的

**Comment by helloworld107** [comment]
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.2.0'

```
    // NOTE: Do not place your application dependencies here; they belong
    // in the individual module build.gradle files
}
```

}

allprojects {
    repositories {
        jcenter()
    }
}

**Comment by helloworld107** [comment]
public interface OriginalRankService
{

```
@GET("index/rank/{type}")
Observable<OriginalRankInfo> getOriginalRanks(@Path("type") String type);
```

}
就是这个接口有问题
H:\SangGuiGu\bilibili-master-x\app\src\main\java\com\hotbitmapgg\ohmybilibili\network\api\OriginalRankservice.java
Error:(22, 8) 错误: 类OriginalRankService是公共的, 应在名为 OriginalRankService.java 的文件中声明
Error:Execution failed for task ':app:compileDebugJavaWithJavac'.

> Compilation failed; see the compiler error output for details.
> 加上public也不管用，不像是环境的问题

**Comment by helloworld107** [comment]
解决了，as编译时候的bug,导致那个接口坏掉了，无法被识别，我删除了又重新写了一遍就好了，开源项目的作者都是好人，app非常nice,搜索框的动画好酷炫

**Comment by HotBitmapGG** [comment]
@helloworld107 可以了吧 我是说很奇怪啊 我这边本地编译是好的 刚又检查了一遍代码 应该是没有问题，解决了就好。
