### ISSUE TITLE
小问题

### ISSUE THREAD

**Issue by wcglws** [HotBitmapGG/bilibili-android-client#12]
你好，最近在学习你这个项目，发现个小问题，首先切换到首页 番剧 一栏，然后从首页的任何一个页面切回番剧，番剧页面会自动向上滑动一段距离，请问大神这个是什么梗？

**Comment by HotBitmapGG** [comment]
@wcglws 恩 是有这个问题 晚点我检查下 因为一直在完善其他功能 后边会慢慢优化

**Comment by HotBitmapGG** [comment]
@wcglws 这个问题已经修复了
