### ISSUE TITLE
Project tasks completed progress

### ISSUE THREAD

**Issue by HotBitmapGG** [HotBitmapGG/bilibili-android-client#13]
1.用户界面完善，正在开发中。
 2.搜索界面的完善和优化。
 3.番剧详情界面完善。
 4.直播界面完善和优化。
 5.主题切换和夜间模式填坑。
 6.代码和布局优化。
 7.主页6大模块添加缓存。
 8.分区界面添加推荐页面。
 9.番剧时间表优化，添加追番界面。
 10.已知bug修复，MVP重构。

**Comment by HotBitmapGG** [comment]
用户详情界面完善已经完成。

**Comment by HotBitmapGG** [comment]
追番界面已添加

**Comment by zzzeus** [comment]
我下载了你的源码，可是遇到问题，怎么都无法解决。
FAILURE: Build failed with an exception.
- What went wrong:
  Execution failed for task ':app:transformJackWithJackForDebug'.
  
  > com.android.build.api.transform.TransformException: com.android.jack.api.v01.CompilationException: Failed to compile
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
请问怎么解决？找了很多方法都不行

**Comment by HotBitmapGG** [comment]
@zzzeus 因为我升级了2.2的AS，为了支持java8，使用了jack编译，如果你编译不过，把app目录下的build.gradle文件里的  
  jackOptions {
            enabled true
        }
去掉，
添加
buildscript {
    repositories {
        mavenCentral()
        maven { url "https://jitpack.io" }
    }
    dependencies {
            classpath 'me.tatarka:gradle-retrolambda:3.2.5'
    }
}

apply plugin: 'com.android.application'
apply plugin: 'me.tatarka.retrolambda'

**Comment by HotBitmapGG** [comment]
7.主页6大模块添加缓存。
8.分区界面添加推荐页面。
已完成。

**Comment by hlxkurapika** [comment]
OriginalRankservice.java 与 文件中共有接口OriginalRankService 名称不一致，S大小写是不是写错了

**Comment by HotBitmapGG** [comment]
@hlxkurapika  啊，没注意啊，我看下

**Comment by HotBitmapGG** [comment]
@hlxkurapika  啊，没注意啊，我看下

**Comment by HotBitmapGG** [comment]
@hlxkurapika  好了，删除了重新提交了下。

**Comment by nujnay** [comment]
great job

**Comment by beilly** [comment]
@HotBitmapGG, 你用as2.2、java8、jack一起的时候没遇到代码中中文写的在界面显示乱码的问题吗？[Jack doesn't support non-ASCII sources encoding](https://code.google.com/p/android/issues/detail?id=218892)

**Comment by HotBitmapGG** [comment]
@shibenli 乱码没有遇到过啊 很正常啊

**Comment by beilly** [comment]
@HotBitmapGG 跑起来的时候，那些卸载代码的中文都是乱码（encoding 是utf-8）

**Comment by beilly** [comment]
还有可能就是你电脑的默认编码，这是官方给出的解释：Lukas, Gradle Plugin is not able to set the encoding with JackInProcess true for now. I think it is in the Jack side for now.

**Comment by HotBitmapGG** [comment]
2.搜索界面的完善和优化。 完成

**Comment by xieyucheng** [comment]
请教个问题，我翻页到番剧页面最顶端，然后切换至其他页面比如分区页面，然后再切换回来， 番剧页面总会下滑至新番连载之后的位置，这是怎么回事呢？？？

**Comment by HotBitmapGG** [comment]
@xieyucheng  你好，这个问题以前确实存在，这个在2.2.4版本已经修复了，你可以clone下最新的代码在看下

**Comment by xieyucheng** [comment]
感谢你的回复，最新代码我看了下，那个bug确实解决了，可以告知下具体是改了哪里不，出现这个bug的原因是？？？

**Comment by HotBitmapGG** [comment]
@xieyucheng  是recyclerView抢占焦点导致的

**Comment by beilly** [comment]
@HotBitmapGG ,之前乱码的问题我想我已经解决了。主要是由于我用的中文版本的windows 7，默认的字符集不是utf-8（[Jack has been using the default VM encoding, which on windows is windows-1252](https://code.google.com/p/android/issues/detail?id=218892#c4)）,但是jack暂时又没有提供自定义encoding的api，因此我从AS的配置入手解决的。

![image](https://cloud.githubusercontent.com/assets/7353956/19841798/c048e7d2-9f4b-11e6-9fb2-c3607d2a6db2.png)

添加了

```
-Dfile.encoding=UTF-8
```

指定vm的字符集为UTF-8，当然对于用mac和Linux的同学可能没有这个问题。

**Comment by HotBitmapGG** [comment]
@shibenli 好的，解决了就好，我是mac，所以我确实没遇到这个问题 - -。

**Comment by beilly** [comment]
恩，mac大法好 :+1:

**Comment by beilly** [comment]
jack这东西是好，但是用在生产环境还是要考虑一下。今天试了一下项目，debug环境没问题，release之后混淆的代码就莫名其妙的不对了。

**Comment by luxiao0314** [comment]
不用dataBinding试一下吗

**Comment by RMaple** [comment]
OriginalRankService这个类代码里类名里“Service”写的是“service”，所以报了个小错误，改一下成功运行
