### ISSUE TITLE
用了java8吗（as2.1.2  还要怎么配置 或者说哪个个分支212可以用啊）？

### ISSUE THREAD

**Issue by jiangyongandy** [HotBitmapGG/bilibili-android-client#15]
Error:com.android.jack.frontend.FrontendCompilationException: Failed to compile
    at com.android.jack.Jack.buildSession(Jack.java:978)
    at com.android.jack.Jack.run(Jack.java:496)
    at com.android.jack.api.v01.impl.Api01ConfigImpl$Api01CompilationTaskImpl.run(Api01ConfigImpl.java:102)
    ... 85 more
:app:transformJackWithJackForDebug FAILED
Error:Execution failed for task ':app:transformJackWithJackForDebug'.

> com.android.build.api.transform.TransformException: com.android.jack.api.v01.CompilationException: Failed to compile

**Comment by HotBitmapGG** [comment]
@jiangyongandy 如果你还是2.1.2的话，把`jackOptions {
            enabled true
        }`去掉，然后在app目录下的build.gradle文件里添加`classpath 'me.tatarka:gradle-retrolambda:3.2.5'`，`apply plugin: 'me.tatarka.retrolambda'`,在编译试一下

**Comment by HotBitmapGG** [comment]
buildscript {
    repositories {
        mavenCentral()
        maven { url "https://jitpack.io" }
    }
    dependencies {
        classpath 'me.tatarka:gradle-retrolambda:3.2.5'
    }
}

apply plugin: 'com.android.application'
apply plugin: 'me.tatarka.retrolambda'

@jiangyongandy

**Comment by jiangyongandy** [comment]
@HotBitmapGG  ok,thanks.

**Comment by scyanghe** [comment]
Error:Execution failed for task ':app:transformJackWithJackForDebug'.

> com.android.sched.scheduler.RunnerProcessException: Error during 'JayceInLibraryWriterAll' runner on 'static final class rx.internal.operators.OperatorMerge$MergeSubscriber (OperatorMerge.java:0-0)': GC overhead limit exceeded
> 编译报这种错误怎么处理？
