### ISSUE TITLE
项目中已经使用了rxcache,okhttpclient设置的cache有什么存在的意义呢？

### ISSUE THREAD

**Issue by jiangyongandy** [HotBitmapGG/bilibili-android-client#17]

**Comment by HotBitmapGG** [comment]
rxcache是最近才添加的，okhttp设置的其实没有用，

**Comment by HotBitmapGG** [comment]
@jiangyongandy  详细说一下，使用Rxcache只是在主页的6个模块界面使用，其他界面没有使用，okhttp设置的缓存其实没有用，只不过是我的okhttp的习惯配置，okhttp设置缓存还是要看服务器支不支持缓存，如果服务器支持缓存，请求返回的Response会带有这样的Header:Cache-Control, max-age=xxx,这种情况下我们只需要手动给okhttp设置缓存就可以让okhttp自动帮你缓存了。这里的max-age的值代表了缓存在你本地存放的时间，没有用的原因是这个项目的接口大部分都是我抓包拿到的。

**Comment by jiangyongandy** [comment]
@HotBitmapGG thanks verymuch
