### ISSUE TITLE
首页进去直接蹦了

### ISSUE THREAD

**Issue by liyanfei250** [HotBitmapGG/bilibili-android-client#18]
java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.

**Comment by HotBitmapGG** [comment]
@liyanfei250 你手机是4.4的嘛？

**Comment by HotBitmapGG** [comment]
因为手上只有5.0以上的机器，我用模拟器4.4的确实一打开就崩溃，这个原因还在定位，晚点会修复。
