### ISSUE TITLE
low mem重启时界面重叠

### ISSUE THREAD

**Issue by stay4cold** [HotBitmapGG/bilibili-android-client#2]
![Uploading device-2016-09-07-155715.png…](界面low mem时候重叠啦)

**Comment by stay4cold** [comment]
![device-2016-09-07-155715](https://cloud.githubusercontent.com/assets/9329571/18304294/1d8f1d88-7514-11e6-8c12-f2473577ecba.png)

**Comment by HotBitmapGG** [comment]
@stay4cold 好的，这种情况确实没有做处理，晚点修复

**Comment by HotBitmapGG** [comment]
已修复.
