### ISSUE TITLE
服务器返回来的数据有好多乱码

### ISSUE THREAD

**Issue by cp140521** [HotBitmapGG/bilibili-android-client#22]

**Comment by HotBitmapGG** [comment]
编码问题请参考：

@HotBitmapGG ,之前乱码的问题我想我已经解决了。主要是由于我用的中文版本的windows 7，默认的字符集不是utf-8（Jack has been using the default VM encoding, which on windows is windows-1252）,但是jack暂时又没有提供自定义encoding的api，因此我从AS的配置入手解决的。

image

添加了

-Dfile.encoding=UTF-8

指定vm的字符集为UTF-8，当然对于用mac和Linux的同学可能没有这个问题。
