### ISSUE TITLE
您好 帮我看一下 这个问题怎么解决？

### ISSUE THREAD

**Issue by baoyumin** [HotBitmapGG/bilibili-android-client#23]
Error:(100, 0) Could not find method apt() for arguments [com.jakewharton:butterknife-compiler:8.4.0] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
<a href="openFile:E:\bilibili-android-client-master-x\bilibili-android-client-master-x\app\build.gradle">Open File</a>

我把as改成2.0.0之后出现了这个问题

**Comment by HotBitmapGG** [comment]
这个问题你要自己去引用apt插件，因为as2.2已经支持了，之前版本还不支持
