### ISSUE TITLE
探讨一下，关于b站播放器

### ISSUE THREAD

**Issue by FatPaper** [HotBitmapGG/bilibili-android-client#25]
最近在做播放器这一块，出现很多问题，我在开启MediaCodec后在某些手机上播放一些高码率的视频时，你把播放器切换至后台，此时surfaceview会调destroy，暂停播放器，然后再重后台切换至前台，surfaceview会调create,，开始播放器，流程都没有错，但是就是在某些机型上播放某些视频时，MediaCodec会报状态异常，跟踪代码是在create里设置surface出现的，我看你playView的实现，surfaceview在销毁后，你直接释放掉了播放器，surfaceview重新创建之后又会新建播放器并seek到之前的播放点，这样当然可以，但是这样每次从后台切换至前台后都会有个seek动作，你那没有进度条显示所以不是很明显，有了进度条每次都会先转几秒再开始播放，体验效果不怎么样，我看了B站播放器的效果，感觉它的surfaceView在切换至后台之后并没有被销毁，我猜测它是不是并没有把surfaceview放到activity里而是放在popupwindow里这样

**Comment by FatPaper** [comment]
@HotBitmapGG

**Comment by HotBitmapGG** [comment]
这个问题我确实知道，对于播放器这块，我并没有写的太深入，很多地方都要去做优化，因为目前工作太忙，没有太多时间去搞，后边有时间的话会深入视频播放这块，把这块优化一下

**Comment by FatPaper** [comment]
@HotBitmapGG 有想法，求告知
