### ISSUE TITLE
无法播放视频

### ISSUE THREAD

**Issue by LyonUp** [HotBitmapGG/bilibili-android-client#26]
点击直播：一直黑屏
点击视频：视频缓冲失败，HTTP 404 Not Found

**Comment by HotBitmapGG** [comment]
因为这个接口暂时用不了了，后边会换新的接口，目前工作太忙，没太多时间处理了

**Comment by weiyf** [comment]
什么时候能更新一下视频的接口？或者提供一下接口来源或思路？

**Comment by HotBitmapGG** [comment]
基本上更新不了了，b站官方接口都换了，包都抓不到了 @weiyf
