### ISSUE TITLE
请教：主页布局

### ISSUE THREAD

**Issue by FatPaper** [HotBitmapGG/bilibili-android-client#27]
我也在做一个影音类的app,推荐页布局大体上跟你的布局是一样的，但是它Section的content部分有些是两行两列布局，有些却是两行3列布局，我拿着你的代码修改了一下，效果不是很好，不知道有什么可以指点的，还有就是，按你这种写法，换一批的实现是不是只能全部刷新，不能做到局部刷新某个Section的内容？ @HotBitmapGG

**Comment by HotBitmapGG** [comment]
Section这个库使用的话 针对一些不规则复杂的item列表比较适合，如果想做局部刷新的话 可以针对单独Section去做notify操作，不过我还没试过 - -！ @FatPaper

**Comment by FatPaper** [comment]
主页布局改了下代码已经实现了，取代了我之前用的listview嵌套gridview方式，卡顿也有了明显的改善，我发现这两种方式的最大的区别应该是将item拆分的问题，局部刷新暂时没什么好的做法，如果非要做还的计算出刷新部分在recyclerview里的position,感觉比较麻烦，暂时没做，显示在全部刷新一遍

**Comment by anson39f** [comment]
@FatPaper 您好，楼主的是item都是四个，两行的。你的item行数不同怎么做的？

**Comment by FatPaper** [comment]
@anson39f 控制item个数在这个getContentItemsTotal方法里，至于列数的控制就在`mGridLayoutManager.setSpanSizeLookup(new GridLayoutManager.SpanSizeLookup() {

            @Override
            public int getSpanSize(int position) {
            }
        });`

**Comment by CFM880** [comment]
慕课网《不一样的RecyclerView优雅实现复杂列表布局》也有说到
