### ISSUE TITLE
请教一下recyclerview的问题

### ISSUE THREAD

**Issue by Basakerone** [HotBitmapGG/bilibili-android-client#29]
主页推荐布局，recyclerview有嵌套横向recyclerview，如果横向recyclerview很多，怎么解决横向recyclerview复用的问题？

**Comment by 1242128273wangpeng** [comment]
这项目中的Recyclerview只有添加头尾布局，没有多类型的RecycleView的显示？

**Comment by bemywife** [comment]
这个项目里的Recyclerview有多种item显示的
