### ISSUE TITLE
java.lang.NoClassDefFoundError: com.hotbitmapgg.ohmybilibili.module.video.VideoDetailsActivity$4

### ISSUE THREAD

**Issue by quguangle** [HotBitmapGG/bilibili-android-client#3]
界面可以展示，但是点击任何一个item时就报错，报错原因我大致看了一下，是你的主题导致的。我一开始用的是模拟器（gemnytion--17)你的最低版本为19，当时我就改成17，包了我写的错误，后来我就换成真机测试，满足你的项目的构建，但是结果出现跟原来同样的错误。什么原因？

**Comment by HotBitmapGG** [comment]
你起码把错误日志贴上来吧，让我拿意念去给你改这个问题嘛？ @quguangle

**Comment by HotBitmapGG** [comment]
@quguangle 已经修复,CoordinatorLayout的一个滑动监听方法只能在21以上进行调用，所以在21以下的机器上直接崩溃了，已修改为AppBarLayout的滑动监听方法替换了，目前还没有时间做完整的适配，这个会慢慢完善。
