### ISSUE TITLE
主题切换问题。

### ISSUE THREAD

**Issue by anson39f** [HotBitmapGG/bilibili-android-client#30]
正版的主题切换很好，切换不闪屏，无缝切换的样子。本项目的切换主题会闪屏，能不能优化下，可以研究下正版是怎么实现的么，共享咯。

**Comment by HotBitmapGG** [comment]
主题切换目前用的是support的夜间模式切换，效果不是很好，项目已经集成了b站的 @xyczero大神的主题切换库，但是由于时间关系一直没有完善好，后期会抽时间把这主题切换搞好，近期由于公司任务比较多，所以这个项目一直没怎么维护了，后期有时间会花时间把这个项目更完善 @anson39f

**Comment by xyczero** [comment]
不敢大神，一起加油^.^

**Comment by HotBitmapGG** [comment]
一起加油^.^
