### ISSUE TITLE
在4.4的机器上Translucent Bar显示有很多Bug

### ISSUE THREAD

**Issue by Litten1106** [HotBitmapGG/bilibili-android-client#32]
![](http://oasusatoz.bkt.clouddn.com/17-2-16/82112522-file_1487234931744_11f97.png)

这里是登录界面

![](http://oasusatoz.bkt.clouddn.com/17-2-16/29986175-file_1487234936620_68ff.png)

这里是首页

![](http://oasusatoz.bkt.clouddn.com/17-2-16/61722441-file_1487234941814_20d7.png)

这里是首页任意点击跳转后的二级界面，目测是没有设置 fitSystem="true"

我的手机是Htc one e8, Android版本4.4.2

**Comment by HotBitmapGG** [comment]
恩，这些问题我都知道，我也在下边的说明里说了，在Api21以下可能界面适配有些问题，之前一直没时间做适配 @GiitSmile
