### ISSUE TITLE
请教一下recyclerview的多类型展示,最近写recyclerview的demo,发现多类型的展示，上下滑动会有点较明显的卡顿，用的也是glide，一般要怎么优化才行

### ISSUE THREAD

**Issue by apklearner** [HotBitmapGG/bilibili-android-client#35]
@HotBitmapGG

**Comment by HotBitmapGG** [comment]
@apklearner 你是自己在adapter根据itemType来写的嘛，建议可以参考下一些库，比如drakeet大神的[https://github.com/drakeet/MultiType](MultiType)
