### ISSUE TITLE
MVP框架选用什么比较好?

### ISSUE THREAD

**Issue by weituotian** [HotBitmapGG/bilibili-android-client#38]
不知道用哪个?

**Comment by HotBitmapGG** [comment]
推荐T-MVP @weituotian

**Comment by yuzhongrong** [comment]
tmp 看不懂啊

**Comment by weituotian** [comment]
@HotBitmapGG @yuzhongrong 好
![image](https://cloud.githubusercontent.com/assets/7270968/24585132/65469a86-17b5-11e7-9b96-f55b6c9afb2c.png)
