### ISSUE TITLE
楼主，你检查下，有些图片没有了

### ISSUE THREAD

**Issue by Dreamer206602** [HotBitmapGG/bilibili-android-client#4]
![image](https://cloud.githubusercontent.com/assets/14008096/18411595/2e434104-77ad-11e6-9813-c5b6ba86470e.png)

**Comment by HotBitmapGG** [comment]
@Dreamer206602 这个昨天晚上删除了一些没有用的图片资源，布局文件忘记提交了，抱歉哈

**Comment by HotBitmapGG** [comment]
@Dreamer206602 已提交，因为这两天在搞屏幕适配的东西，有些没有改完就没提交上去，但是忘记了我删了一些没有用到的图片资源了。

**Comment by Dreamer206602** [comment]
好的，我再下载一份
