### ISSUE TITLE
有实现登录功能吗

### ISSUE THREAD

**Issue by yuzhongrong** [HotBitmapGG/bilibili-android-client#40]
有实现的话 我最近在做项目正好学习下

**Comment by yuzhongrong** [comment]
跟大神后学习下

**Comment by HotBitmapGG** [comment]
@yuzhongrong 没有做登录 因为考虑只是个A货 登不登录没有什么区别 - -

**Comment by yuzhongrong** [comment]
我感觉这个做个登录后 模块后 就碉堡天了 我会吧你这套项目从头学习到尾

**Comment by yuzhongrong** [comment]
麻烦大神有空帮忙弄下 既然做了 而且快要成功做完整了 那么 能不能 满足下我们呢  到后面我会在项目中使用你这个 抽出来作为模块

**Comment by yuzhongrong** [comment]
因为我这边需要参考下大神的登录模块

**Comment by yuzhongrong** [comment]
崇拜你

**Comment by yuzhongrong** [comment]
还有那个视频不能播放 404 报错

**Comment by xiahuaijia** [comment]
登录用上RSA 加密就可以了 @yuzhongrong

**Comment by yuzhongrong** [comment]
rsa 是什么

**Comment by xiahuaijia** [comment]
RSA公钥加密算法  现在大多数网站都是用这个加密方式 B站的也是 @yuzhongrong

**Comment by HotBitmapGG** [comment]
@yuzhongrong 登录不好做啊，涉及到用户个人信息，所以搞不了，还有视频不能播放是因为接口挂了，新的接扣抓包也抓不到了，所以基本放弃了，目前这个项目仅限于大家学习交流用，我也没太多时间来维护了。

**Comment by xiahuaijia** [comment]
登录很容易啊 我已经做出来了  而且很多地方都有源码的 @HotBitmapGG

**Comment by HotBitmapGG** [comment]
@xiahuaijia _那来个pr吧，哈哈

**Comment by xiahuaijia** [comment]
我暂时不想公开 准备吧视频获取算法的破解出来在公开
@HotBitmapGG 

这里有其他语言的源码(易语言)参考你可以看一下
hash 有效期20秒 超时返回-622  密码加密过期

http://bbs.125.la/forum.php?mod=viewthread&tid=13997071&extra=page=1

**Comment by yuzhongrong** [comment]
抓紧公开 我等着学习呢  高手

**Comment by whyalwaysmea** [comment]
@xiahuaijia  等你公开的时候记得@ 一下啊

**Comment by xiahuaijia** [comment]
@whyalwaysmea @yuzhongrong @HotBitmapGG 

现在弄了一个API  和  C#  Python JavaScript库的
https://github.com/xiahuaijia/bilibili-Login

应该够用了吧
