### ISSUE TITLE
开个issue 来吐槽，吐槽使人进步

### ISSUE THREAD

**Issue by VectorWen** [HotBitmapGG/bilibili-android-client#42]
```java
public class ActivityCenterActivity extends RxBaseActivity {

  @BindView(R.id.toolbar)
  Toolbar mToolbar;

  @BindView(R.id.swipe_refresh_layout)
  SwipeRefreshLayout mSwipeRefreshLayout;

  @BindView(R.id.recycle)
  RecyclerView mRecyclerView;

  private int pageNum = 1;

  private int pageSize = 20;

  private View loadMoreView;

  private List<ActivityCenterInfo.ListBean> activityCenters = new ArrayList<>();

  private ActivityCenterAdapter mAdapter;

  private HeaderViewRecyclerAdapter mHeaderViewRecyclerAdapter;

  private boolean mIsRefreshing = false;

  private EndlessRecyclerOnScrollListener mEndlessRecyclerOnScrollListener;

}
```
1. 去掉部分空行代码会显得更有层次感
2. ButterKnife 推荐的是一行绑定
3. 属性命名也是醉了，一时有m，一时没有，boolean 属性反而又加了m

```java
public class ActivityCenterActivity extends RxBaseActivity {

    @BindView(R.id.toolbar) Toolbar mToolbar;
    @BindView(R.id.swipe_refresh_layout)SwipeRefreshLayout mSwipeRefreshLayout;
    @BindView(R.id.recycle) RecyclerView mRecyclerView;

    private int mPageNum = 1;
    private int mPageSize = 20;
    private View mLoadMoreView;
    private boolean isRefreshing = false;
    
    private List<ActivityCenterInfo.ListBean> mActivityCenters = new ArrayList<>();
    private ActivityCenterAdapter mAdapter;
    private HeaderViewRecyclerAdapter mHeaderViewRecyclerAdapter;
    private EndlessRecyclerOnScrollListener mEndlessRecyclerOnScrollListener;

}
```

**Comment by VectorWen** [comment]
基本看不到注释，不管逻辑是否简单，这就是不好的习惯。

**Comment by CFM880** [comment]
@VectorWen 你应该看看这个
[为何我暂停了维护 Python 社区的志愿者工作](https://mp.weixin.qq.com/s?__biz=MjM5NzM0MjcyMQ==&mid=2650068528&idx=2&sn=bad467d1f2997b326e5e3fe764fe811c&chksm=bedb0d5e89ac84482e3e0a2821d6d344ade29fac6529bb7eefac5839c6fcfb7f28dd7caf2095&mpshare=1&scene=1&srcid=1118rWyPr6YaG3ujqB1KxTp8&key=2bfdd394c9253d2078c3272ab859b5384ad496b50c23ed4f15db1d9df4199a88e10a77a40bff40f7be66d87c53805a9f991c965e244ba2effb2f636e8a9e69399212fceb5a4643e91c77331b1cf39776&ascene=0&uin=MTY4MDE1OTQ2MQ%3D%3D&devicetype=iMac+MacBookPro11%2C4+OSX+OSX+10.12.4+build(16E195)&version=12020510&nettype=WIFI&fontScale=100&pass_ticket=b5gfbqJq1aUb9h3%2FIj5%2FDQGYPbJDKiRdL7i%2BQOfuSmmFw8%2B7bfWHm3WXwdOSWtZ8)

**Comment by VectorWen** [comment]
@CFM880 又一个拿别人的感悟来当挡箭牌，阿弥陀佛、善哉善哉。

**Comment by CFM880** [comment]
自己没做到，没有要求理由要求别人做到，不跟你喷，多说无益 @VectorWen

**Comment by VectorWen** [comment]
@CFM880 对不起，就是因为我做到了，我才说的。是不是你自己做不到，就认为我做到了呢？

**Comment by VectorWen** [comment]
@CFM880 对不起，就是因为我做到了，我才说的。是不是你自己做不到，就认为我做不到了呢？

**Comment by CFM880** [comment]
哈哈 @VectorWen talk is cheap show me your code

**Comment by HotBitmapGG** [comment]
@VectorWen 感谢你的吐槽，毕竟每个人代码风格都不一样，当时写这个项目的时候，也是去年年初才接触到那些热门库的时候写的，那时候对于很多库确实还是熟悉的阶段，肯定有写得不好的地方，开源本来就是互相学习，有好的优化或者建议，欢迎pr。

**Comment by HotBitmapGG** [comment]
@VectorWen 对于注释这一块，当然我是个不太喜欢写注释的人，这确实是个很不好的习惯，但是对于一些基本的注释我还是有写的啊。

**Comment by VectorWen** [comment]
@HotBitmapGG 对的，相互学习。标题也说了，为了进步。

**Comment by RedWolfChao** [comment]
老铁,恕我愚昧.照着你的SplashActivity的xml敲,发现 图片太大,就是出不来,请问你是怎么让这两个图片在屏幕中间显示而不贴边的. @HotBitmapGG

**Comment by HotBitmapGG** [comment]
@RedWolfChao 你的出来是什么效果的啊，贴个图看下，启动页的就一个大图加一个logo啊 大图居中显示，logo设置到底部然后给了个底部的外边距就这样而已啊

**Comment by RedWolfChao** [comment]
![default](https://cloud.githubusercontent.com/assets/17734306/25426326/515f9c3a-2aa1-11e7-8830-f443444827c4.png)

**Comment by RedWolfChao** [comment]
@HotBitmapGG 如图所示....

**Comment by HotBitmapGG** [comment]
@RedWolfChao 把两张图片放到drawable-xxhdpi下边

**Comment by RedWolfChao** [comment]
@HotBitmapGG ...无奈,可否稍微说一下原理,我竟从没这么干过..

**Comment by HotBitmapGG** [comment]
@RedWolfChao - - ，这是最基础的适配啊 这两张图你看下分辨率就知道要放在xxhdpi下啊

**Comment by RedWolfChao** [comment]
好吧,我想我该去看看适配相关的知识了...无奈开发许久,没碰过适配...万分感谢!

**Comment by HotBitmapGG** [comment]
您的吐槽我都已经修改，欢迎继续吐槽，这个先关了 - -！
