### ISSUE TITLE
okhttp 拦截器的缓存配置问题

### ISSUE THREAD

**Issue by yibeiliu** [HotBitmapGG/bilibili-android-client#43]
这一段
`private static class CacheInterceptor implements Interceptor {

        @Override
        public Response intercept(Chain chain) throws IOException {

            // 有网络时 设置缓存超时时间1个小时
            int maxAge = 60 * 60;
            // 无网络时，设置超时为1天
            int maxStale = 60 * 60 * 24;

            Request request = chain.request();

            if (CommonUtil.isNetworkAvailable(BilibiliApp.getInstance())) {
                //有网络时只从网络获取
                request = request.newBuilder()
                        .cacheControl(CacheControl.FORCE_NETWORK)
                        .build();
            } else {
                //无网络时只从缓存中读取
                request = request.newBuilder()
                        .cacheControl(CacheControl.FORCE_CACHE)
                        .build();
            }
            Response response = chain.proceed(request);
            if (CommonUtil.isNetworkAvailable(BilibiliApp.getInstance())) {
                response = response.newBuilder()
                        .removeHeader("Pragma")
                        .header("Cache-Control", "public, max-age=" + maxAge)
                        .build();
            } else {
                response = response.newBuilder()
                        .removeHeader("Pragma")
                        .header("Cache-Control", "public, only-if-cached, max-stale=" + maxStale)
                        .build();
            }
            return response;
        }
    }`

测试后发现无网的情况下刷新所读取的 cache 失效时间是 maxAge ，换句话说，` Response response = chain.proceed(request);` 之后的代码在无网络的时候是运行不到的，我在这块研究的也不太透彻，想磋商一下解决方案...还望赐教啊

**Comment by liangjingkanji** [comment]
Okhttp不支持Post缓存吧

**Comment by yibeiliu** [comment]
@liangjingkanji 我说的都是 GET 请求哦~
