### ISSUE TITLE
自动安装未知应用Leaks?

### ISSUE THREAD

**Issue by Yagami2013** [HotBitmapGG/bilibili-android-client#44]
启动哔哩哔哩后会自动安装下面这个应用，打开这个应用如图二，提示"Leaks in com.hotbitmapgg.ohmyb..."
请问这是什么东东？搜索了res文件夹并没看到这个图标
![alt text](https://github.com/Yagami2013/pictures/blob/master/bilibili-android-client/880817326788959344.jpg)
![image](https://github.com/Yagami2013/pictures/blob/master/bilibili-android-client/363604672666000888.jpg)

**Comment by TakWolf** [comment]
看这个：https://github.com/square/leakcanary
