### ISSUE TITLE
关于素材问题

### ISSUE THREAD

**Issue by monkingxue** [HotBitmapGG/bilibili-android-client#45]
看到聚聚的这个项目觉得很厉害，自己也想实现一个 mobile web 版的 bilibili，但是想问聚聚的素材从哪里来呢？就是这些图片和设计图，找了半天没找到啊 sigh

**Comment by HotBitmapGG** [comment]
@monkingxue 我是直接把b站的apk包解压就拿到资源文件了，你可以去市场上下个apk，然后解压出来，res目录下边就是图片资源了

**Comment by monkingxue** [comment]
@HotBitmapGG 吼的，蟹蟹~
