### ISSUE TITLE
没法播放 是改变了https安全认证还是添加了防盗链

### ISSUE THREAD

**Issue by yuzhongrong** [HotBitmapGG/bilibili-android-client#46]

**Comment by HotBitmapGG** [comment]
没法播放这是个老问题了，我用的是一个开源的b站api获取的b站播放器地址，但是后来b站大更新后接口已经挂掉了，这个作者也没有在跟进了，所以视频播放不了，我自己也试了抓包拿地址，但是现在b站的接口都是https的了，我用charles打了证书去抓也没用，所以这个地址暂时没有解决方案，加上今年又换了工作比较忙，一直没时间维护这个项目，等后期有时间会研究一下。 @yuzhongrong

**Comment by yuzhongrong** [comment]
好的 多谢

**Comment by wusir-china** [comment]
多谢up主
