### ISSUE TITLE
内容搜索的疑惑

### ISSUE THREAD

**Issue by lpslpsl** [HotBitmapGG/bilibili-android-client#47]
抓包是发现有抓到数据的
比如搜索到四重奏，
ui上确实什么都没搜到的2233娘！
附上返回的json是`{"code":0,"data":{"trackid":"9870625618631225261","page":1,"nav":[{"name":"番剧","total":2,"pages":1,"type":1},{"name":"UP主","total":5,"pages":1,"type":2},{"name":"影视","total":2,"pages":1,"type":3}],"items":{"season":[{"title":"苍之彼方的四重奏","cover":"https://i0.hdslb.com/bfs/bangumi/fa218bbc1f73d86824dddb3048691058a82ccf25.jpg","uri":"bilibili://bangumi/season/3106","param":"3106","goto":"bangumi","finish":1,"started":0,"index":"12","newest_cat":"tv","newest_season":"TV","cat_desc":"TV(1) ","total_count":12,"status":0,"attentions":0},{"title":"夜樱四重奏","cover":"https://i0.hdslb.com/bfs/bangumi/801ce571558800627e9b5f70c3a52ae7a09ae81d.jpg","uri":"bilibili://bangumi/season/472","param":"472","goto":"bangumi","finish":1,"started":0,"index":"3","newest_cat":"ova","newest_season":"OVA2","cat_desc":"TV(2) OVA/OAD/SP(2)","total_count":3,"status":0,"attentions":0}],"movie":[{"title":"生命四重奏","cover":"https://i0.hdslb.com/bfs/bangumi/6e620aa1622c718ba192c1ba2c96c62ec8f52cff.jpg","uri":"bilibili://video/3034521","param":"3034521","goto":"av","started":0,"total_count":0,"desc":"依山傍海的卡拉布里亚岛的小村子，住着一个已经时日不多的老牧羊人，他病了，他坚信他找到了续命的良药，他从教堂的地板上收集灰尘，每晚就水喝下。在一个羊圈里的一小片黑土地上，一只山羊生下了一只小白山羊，生命最初的不适只持续了一小段时间，它的眼睛立刻便睁开了，它的蹄子已经可以支撑身体的重量。整个村子的生活都被这个新生命的到来而充满了希望","screen_date":"2000-11-22 08:00:00","area":"法国","cover_mark":"免费观看","actors":"阿兰·卡瓦利埃、Jean-Louis Faure、Michel Labelle","staff":"导演： 阿兰·卡瓦利埃\n编剧： 阿兰·卡瓦利埃","length":88,"status":2,"attentions":0}],"archive":[{"title":"《四重奏》真的是神作吗？5分钟带你看完最近超火的日剧","cover":"https://i0.hdslb.com/bfs/archive/bf7b0f4cefcb1803b9467ad28ce059b92b64b2b4.jpg","uri":"bilibili://video/9450628","param":"9450628","goto":"av","play":24878,"danmaku":21,"author":"追剧侠","started":0,"total_count":0,"desc":"《四重奏》以四人的单相思为感情线，在不经意生活中勾勒出一幕幕人性的温情片段。四人从心怀不轨的结识到相互信任，让人体会到各种真实生活中的谎言，但谎言背后却是真性情","duration":"5:3","status":0,"attentions":0},{"title":"【5分钟人物os解说】日剧 《四重奏》 小心！会入坑的！","cover":"https://i0.hdslb.com/bfs/archive/ca9cf0349be80467965f50029aed739010017956.jpg","uri":"bilibili://video/8986533","param":"8986533","goto":"av","play":30482,"danmaku":125,"author":"DanDan·酱","started":0,"total_count":0,"desc":"抱歉又更晚了！不过四重奏好看！让我一不小心就入了日剧的坑！","duration":"4:58","status":0,"attentions":0},{"title":"【日剧/四重奏/ED】成人的法则【翻唱合集】（更新中）","cover":"https://i0.hdslb.com/bfs/archive/eb9044b79fc030c624fe036ff2db90c81c463170.png","uri":"bilibili://video/8918963","param":"8918963","goto":"av","play":15092,"danmaku":45,"author":"千夏晴香","started":0,"total_count":0,"desc":"http://www.youtube.com/watch?v=3TAXt7QQ7tg（其余链接分P简介） 最近质量较好的几个翻唱","duration":"30:8","status":0,"attentions":0},{"title":"【2016冬季日剧】四重奏~.预告【@FIX字幕侠】","cover":"https://i0.hdslb.com/bfs/archive/c89ef71c94a400d9cb95036b07320ee7d9e14149.jpg","uri":"bilibili://video/8033457","param":"8033457","goto":"av","play":33645,"danmaku":10,"author":"b站FIX字幕侠","started":0,"total_count":0,"desc":"FIX字幕侠 某天，忽然相遇的四个男女。\n这群人未能实现梦想，也未曾到过人生巅峰，驻足于平缓的下坡道前。他们四人决定组成四重奏，并一起在轻井泽生活。\n然而这个“偶然”中隐藏着巨大的秘密。","duration":"0:32","status":0,"attentions":0},{"title":"四重奏#松隆子#满岛光#高桥一生#松田龙平#看日剧学日语#一会日语学习","cover":"https://i0.hdslb.com/bfs/archive/aca26e4d5d64b4e9b00c51ba1f4cc77a44d37b05.jpg","uri":"bilibili://video/8744476","param":"8744476","goto":"av","play":51747,"danmaku":50,"author":"高贵冷艳教主一会","started":0,"total_count":0,"desc":"一会酱学习群230659050 一会酱qq824980948 \n一会酱周六晚上21：00直播公开课https://ke.qq.com/course/119258#term_id=100130590\n一会酱B站直播间：http://live.bilibili.com/372645","duration":"51:39","status":0,"attentions":0},{"title":"日劇四重奏 1-5話 官方濃縮版","cover":"https://i0.hdslb.com/bfs/archive/9c4adf7603351e5e0ee45115d159b7e77b6bd0fe.jpg","uri":"bilibili://video/8631718","param":"8631718","goto":"av","play":7795,"author":"cmyk8823","started":0,"total_count":0,"desc":"https://www.youtube.com/watch?v=I-FVSdSKX7c\u0026amp;feature=youtu.be \n今からでもまだ間に合う 6分間スペシャルダイジェスト!! 火曜10時 『カルテット』いよいよ後半戦に突入!【TBS】\n【１〜５話SPダイジェスト】\nカルテットも次週からいよいよ後半戦に突入します！\n１話から５話までの、６分間のスペシャルダイジェストを公開しました！","duration":"6:32","status":0,"attentions":0},{"title":"【四重奏主题曲完整\u0026ed】中日歌词版 『成人的法则』","cover":"https://i0.hdslb.com/bfs/archive/41aa6a31d24c182e1e19a148692343355aacb3ee.jpg","uri":"bilibili://video/8337142","param":"8337142","goto":"av","play":89059,"danmaku":326,"author":"一米月光1997","started":0,"total_count":0,"desc":"很喜欢的剧 完整版是ed+剧01cut（剪片子真是みぞみぞできました\n若有翻译错误，还请赐教～网易云里可以听完整版啦\n『おとなの掟』\n  歌：松たか子　満島ひかり　松田龍平　高橋一生 \n詞／曲：椎名林檎 \n\n翻译制作：一米月光1997","duration":"5:11","status":0,"attentions":0},{"title":"这部被各大公众号疯转的神剧《四重奏》，台词既丧心又戳心","cover":"https://i0.hdslb.com/bfs/archive/3522961b253f7b8fe2c0f6f5b9073bbd1680dad4.jpg","uri":"bilibili://video/8797979","param":"8797979","goto":"av","play":19987,"danmaku":40,"author":"知引mm","started":0,"total_count":0,"desc":"没时间刷《四重奏》没关系，5分钟告诉你，这部神剧都讲了什么？","duration":"5:13","status":0,"attentions":0},{"title":"【中日字幕】[四重奏ED] 成人法则","cover":"https://i0.hdslb.com/bfs/archive/b6ee844a0d5c3419cc5a799ca32749543a1758ec.jpg","uri":"bilibili://video/8504134","param":"8504134","goto":"av","play":32288,"danmaku":93,"author":"ll阿祈ll","started":0,"total_count":0,"desc":"おとなの掟_成人法则\n4月22日更新：日语字幕已根据官方歌词订正 48s音画不同步问题已修复\n视频及字幕制作：阿祈\n请勿二传二改","duration":"3:26","status":0,"attentions":0},{"title":"【四重奏】ED合集","cover":"https://i0.hdslb.com/bfs/archive/e093842418cd48dcf9e2ca5655b600d142600fcd.jpg","uri":"bilibili://video/9326990","param":"9326990","goto":"av","play":5096,"danmaku":1,"author":"里猫","started":0,"total_count":0,"desc":"片源来自fix字幕组","duration":"3:31","status":0,"attentions":0},{"title":"【完整版】（中日歌词）日剧四重奏ED 成人的准则 Doughnuts Hole","cover":"https://i0.hdslb.com/bfs/archive/aaf567b4c41d50d7ddd21f1ba0b21899aae672b1.jpg","uri":"bilibili://video/8456300","param":"8456300","goto":"av","play":15728,"danmaku":98,"author":"曼熱咖啡","started":0,"total_count":0,"desc":"四重奏 おとなの掟 \n已翻译\n四重奏 BGM/OST 精选：av8502388","duration":"3:26","status":0,"attentions":0},{"title":"《四重奏》ED-成人法则 带字幕 日文/渣中文","cover":"https://i0.hdslb.com/bfs/archive/73518b0a991d042d765e4a8a29faa96faeca577e.jpg","uri":"bilibili://video/8090015","param":"8090015","goto":"av","play":20302,"danmaku":54,"author":"阿良良木历sca","started":0,"total_count":0,"desc":"站里的没字幕，就随手贴了日文和渣中文","duration":"1:43","status":0,"attentions":0},{"title":"【原声音乐】fox capture plan -《四重奏》(Quartet)Original Soundtrack","cover":"https://i0.hdslb.com/bfs/archive/2688fefa4215c85c6d9842af79d6787d37ab4527.png","uri":"bilibili://video/9364859","param":"9364859","goto":"av","play":6056,"danmaku":8,"author":"太安静会窒息斯基","started":0,"total_count":0,"desc":"曲包自取 链接：http://pan.baidu.com/s/1eRUGiK6 密码：h5yv\r\n匆忙浮躁的都市中，四个与音乐相关的男男女女看似偶然般地邂逅了，他们分别是第一小提琴手卷真纪、大提琴手世吹雀、中提琴手家森谕高以及第二提琴手别府司。仿佛是对音乐的共同志向，他们组建了名为“甜甜圈洞”的四重奏乐队，暂时落脚于别府家位于轻井泽的别墅，过起了与世隔绝的人生。然而四个人终究无法超脱世俗存在，除了最基本的吃饭问题，每个人似乎都被各自的秘密所牵扯纠缠。。。","duration":"77:11","status":0,"attentions":0},{"title":"[治愈向 四重奏 满岛光]因为你我对这世界稍微有点期待/我曾想过一了百了","cover":"https://i0.hdslb.com/bfs/archive/87e835379a86472b8243d945e27be0ef96808715.jpg","uri":"bilibili://video/8473020","param":"8473020","goto":"av","play":11822,"danmaku":82,"author":"离酱的本命是SD呀","started":0,"total_count":0,"desc":"   -\u0026amp;lt;我曾想过一了百了。失败的过去， 复杂的人际关系，冰冷的言语。生而为人，如此不堪。我曾想过一了百了，因为你这样的人存在于世上，我对这个世界稍微有点喜欢和期待\u0026amp;gt;-\n\n  我想要微笑面对这个世界。","duration":"4:49","status":0,"attentions":0},{"title":"2017冬季档日剧《四重奏》15秒预告（松隆子 满岛光 高桥一生 松田龙平）","cover":"https://i0.hdslb.com/bfs/archive/4439d126b85e6b26606240a3de3d2553f8d9d2fb.jpg","uri":"bilibili://video/7515897","param":"7515897","goto":"av","play":14587,"danmaku":30,"author":"wangkk","started":0,"total_count":0,"desc":"TBS 2016冬季日剧四重奏15秒预告（松隆子 满岛光 高桥一生 松田龙平）","duration":"0:17","status":0,"attentions":0},{"title":"男孩四重奏 Boy Quartette(2012)","cover":"https://i0.hdslb.com/bfs/archive/d4d9c95a1f89e2a6d2de6c8d3909140314611942.jpg","uri":"bilibili://video/2049617","param":"2049617","goto":"av","play":44345,"danmaku":2684,"author":"不是天才是地才","started":0,"total_count":0,"desc":"直传 第一重奏：夏日的序章  幸运蓝Good Blue 第二重奏：暗恋行板 爱之初，欲本善 第三重奏：梦魇交响乐 牛仔惊魂 cowboy 第四重奏：飘淼安魂曲 戴维与斯图 Davy and Stu   四部以青春男孩为主题的最优秀的短片，分别来自美国、法国、德国与瑞典。让我们一起重听荷尔蒙跳动的乐章吧，那些懵懂的、温热的、掺揉甜蜜和苦涩的男孩故事，其实一直存在于我们的记忆。","duration":"117:0","status":0,"attentions":0},{"title":"【光妹实拍】四重奏玩多米诺雪糕棒＋多视角","cover":"https://i0.hdslb.com/bfs/archive/f0c139b54b5cc8c38110f7727341ebd11e328c9f.jpg","uri":"bilibili://video/9223227","param":"9223227","goto":"av","play":13381,"danmaku":35,"author":"Ringa飽丶","started":0,"total_count":0,"desc":"【公式】火曜ドラマ『カルテット』3_21‏ @quartet_tbs\nリクエスト多数につき公開します！！","duration":"1:26","status":0,"attentions":0},{"title":"『四重奏』 Tune For A Found Harmon完整版","cover":"https://i0.hdslb.com/bfs/archive/bdda111d36de69fe2aabf189400d22bff76f0d8a.jpg","uri":"bilibili://video/9331112","param":"9331112","goto":"av","play":6647,"danmaku":12,"author":"烂柯人啊_","started":0,"total_count":0,"desc":"Youtube\n沉迷四重奏无法自拔，就开始听OST，特别喜欢这首Tune For A Found Harmon，听说油管上有小提琴完整版就搬下来了，希望大家喜欢啊哈哈哈哈","duration":"2:34","status":0,"attentions":0},{"title":"梦魇】模拟人生4 日剧四重奏别墅","cover":"https://i0.hdslb.com/bfs/archive/40adbb49473053dd15fe2ef924a250fb2d363cc8.jpg","uri":"bilibili://video/11147587","param":"11147587","goto":"av","play":36,"author":"梦魇魇魇魇魇魇魇魇","started":0,"total_count":0,"desc":"有很久没有发视频了~前两天突发奇想还原一下喜欢的日剧建筑看看~本来录制了一个建造视频的但是因为软件原因没有录制成功，所以就简单给大家介绍一下这个房子~如果喜欢可以在模拟工坊里下载到，要开自定义内容才行哦~因为有一些不影响还原度的小零件用了mod。\n如果喜欢记得给我投币哟(＾Ｕ＾)ノ~","duration":"14:34","status":0,"attentions":0},{"title":"【四重奏/家雀】和你的美好回忆，早已成为我心脏的一部分","cover":"https://i0.hdslb.com/bfs/archive/02f3719f8350aa39a221fcb1a7ddb8fd1ead6c46.jpg","uri":"bilibili://video/11128478","param":"11128478","goto":"av","play":67,"author":"是啾啾咩","started":0,"total_count":0,"desc":"这个视频早就想剪了）都几个月过去了 终于有时间了。\n看四重奏的时候就非常喜欢家森和小雀 还哭过几次。（被SAJ和章鱼烧虐的不行）。BGM是RADWIMPS的《有心論》。用掏空心脏的歌词和继续emmm的脑补合成了这样的一个故事）一个【相识相知相恋到分手】的故事，过程从单恋到热恋到结束（没谈过恋爱的我哭了。冷色调是现在（是用两人的演奏串起来的）暖色调和黑白是回忆。\n标题是取自于歌曲中，啊。 你还在我的心脏里，使我活着，给予我爱。\n嗯 要幸福啊。\n谢谢观看w","duration":"4:13","status":0,"attentions":0}]}},"message":"","ttl":1}`

**Comment by HotBitmapGG** [comment]
@lpslpsl 你好，一直没时间处理，今天看了一下，后台搜索返回的数据变了，我这边已经修改了，现在可以搜索了

**Comment by HotBitmapGG** [comment]
[https://github.com/HotBitmapGG/bilibili-android-client/commit/3857afcd765d4a11781dc1b6fede525b21b8e2f7](url)
