### ISSUE TITLE
emptyView problem

### ISSUE THREAD

**Issue by hkq325800** [HotBitmapGG/bilibili-android-client#5]
在有网络时正确获取数据后 在无网络下进行刷新emptyView在tab推荐和直播中显示错误 与番剧中不同

**Comment by hkq325800** [comment]
在首页中将toolbar收上去 在共用activity的"我的收藏"、"历史记录"、"关注的人"等中toolbar也不显示了

**Comment by HotBitmapGG** [comment]
@hkq325800 好的，收到，马上修复

**Comment by HotBitmapGG** [comment]
@hkq325800 第二个问题，刚才看了B站的实现，我之前的做法确实有点问题，晚点重新把这个整体结构改下，感谢提的建议。

**Comment by HotBitmapGG** [comment]
@hkq325800 问题已修复。
