### ISSUE TITLE
主题选择CardPickerDialog没有用啊

### ISSUE THREAD

**Issue by CharlesWWT** [HotBitmapGG/bilibili-android-client#50]
我把主题选择你注释掉的代码打开了，发现主题选择功能没有实现

      case R.id.item_theme:
//         主题选择
         CardPickerDialog dialog = new CardPickerDialog();
         dialog.setClickListener(this);
         dialog.show(getSupportFragmentManager(), CardPickerDialog.TAG);
        return true;

**Comment by HotBitmapGG** [comment]
恩，当时只做了一半，要实现的话，整个项目的控件都要修改
