### ISSUE TITLE
咨询点儿小问题

### ISSUE THREAD

**Issue by xfhy** [HotBitmapGG/bilibili-android-client#61]
1, 好多地方应该用switch的,为什么用if else呢
2, adapter中这个为什么不判断null呢
3, 要是用MVP的话就更完美啦
4, 谢谢你的无私奉献,学到了很多

> @Override
    public int getItemCount() {
        return comments.size();
    }

**Comment by xfhy** [comment]
番剧详情界面的时间显示为1970-01-18 17:52

**Comment by HotBitmapGG** [comment]
额，解答下，1.这个算个人习惯吧，不过不是好习惯 - -，2.adapter没有判空，是我代码不够严谨，当然这个项目单纯的只是学习的，所以写的时候没有太过严谨，3.当时写的时候，还没有熟悉MVP，等熟悉了后，想改这个项目，发现工作量实在太大，所以放弃了，4.谢谢，这个项目因为时间关系已经不维护了，所以，能对你有所帮助还是挺好的。 @xfhy

**Comment by xfhy** [comment]
thank you
