### ISSUE TITLE
视频播放问题

### ISSUE THREAD

**Issue by HotBitmapGG** [HotBitmapGG/bilibili-android-client#9]
视频可能暂时播放不了，获取的视频播放的地址被权限了

**Comment by Temoa** [comment]
我的也出现了问题,能够获取到视频的播放地址,但是加载的非常慢,不知道B站方面是不是限制了

**Comment by HotBitmapGG** [comment]
是的，目前暂时用不了了，我在找别的办法

**Comment by Temoa** [comment]
找到方法了吗?我抓自己APP 得到的APPKEY 和APP_SECRET ,用MD5进行sign算法都得不到正确的url

**Comment by HotBitmapGG** [comment]
@Temoa 暂时没有，我猜想的原因是b站出了大会员业务，所以可能获取一些视频地址的接口被权限掉了，因为通过cid获取视频接口地址返回的有3个视频url，标清 ，高清，超清，我估计是这个原因，但是具体还没有好的办法了

**Comment by Temoa** [comment]
@HotBitmapGG 找到了暂时还能使用的方法,参考这个项目[BiliDan](https://github.com/m13253/BiliDan)  里面获取视频地址的方法.也有可能只是换了没有被权限的APPKEY 和APPSEC

**Comment by HotBitmapGG** [comment]
@Temoa  好的 晚点有时间我试下

**Comment by HotBitmapGG** [comment]
视频播放问题已解决
